#!/bin/bash

set -e
set -o nounset

container=$(basename $(pwd))-dev

if ! docker inspect $container >&/dev/null; then
  echo Creating $container
  docker create \
    --name $container \
    --volume $(pwd):/workspace \
    --workdir /workspace \
    rust:1.30.1-slim-stretch \
    sleep 3600
fi

docker start $container 1>&2 || true

exec docker exec -it $container $(basename $0) "$@"
